dependencies:
- name: fmtok8s-agenda
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.34
- name: fmtok8s-c4p
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.44
- name: fmtok8s-api-gateway
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.46
- name: fmtok8s-email
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.20
